openshift/cluster-image-registry-operator

cmd/cluster-image-registry-operator/main.go
pkg/generate/apply.go
pkg/generate/clusterrole.go
pkg/generate/clusterrolebinding.go
pkg/generate/configmap.go
pkg/generate/route.go
pkg/generate/secret.go
pkg/generate/service.go
pkg/generate/serviceaccount.go
pkg/generate/state.go
pkg/generate/utils.go
pkg/operator/bootstrap.go
pkg/operator/complete.go
pkg/operator/handler.go

* Add resource finalizer;
* Bugfixes;

Improve registry operator

---

pkg/generate/route.go
pkg/operator/bootstrap.go
pkg/storage/filesystem/filesystem.go
pkg/storage/storage.go

Prohibit the change of storage subtype

---

pkg/operator/handler.go

Create image-registry deployment by default

---

cmd/cluster-image-registry-operator/main.go
pkg/operator/handler.go

Fixes: https://github.com/openshift/cluster-image-registry-operator/issues/43
Disclaimer: https://gist.github.com/legionus/0dc3335208a7567bbb9f01d2ed94e673

Update image-registry status based on deployment status

---

cmd/cluster-image-registry-operator/main.go
deploy/00-crd.yaml
pkg/clusteroperator/clusteroperator.go
pkg/metautil/humanname.go
pkg/operator/finalizer.go
pkg/operator/handler.go
pkg/resource/podtemplatespec.go
pkg/resource/state.go

Cluster-scoped image resource

---

pkg/apis/imageregistry/v1alpha1/types.go
pkg/clusterconfig/clusterconfig.go
pkg/operator/bootstrap.go
pkg/storage/azure/azure.go
pkg/storage/emptydir/emptydir.go
pkg/storage/filesystem/filesystem.go
pkg/storage/gcs/gcs.go
pkg/storage/s3/s3.go
pkg/storage/storage.go
pkg/storage/swift/swift.go
test/e2e/aws_test.go

Set Status.ManagedStorage on the registry operator custom resource

---

pkg/operator/bootstrap.go
pkg/operator/controller.go
pkg/operator/finalizer.go

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1653563

Recreate CR when it is deleted

---

deploy/04-operator.yaml
deploy/08-ca-daemonset.yaml

fixes https://github.com/openshift/cluster-image-registry-operator/issues/100

add pod priorities

---

pkg/storage/s3/s3.go
test/e2e/aws_test.go

- Enables default encryption on the S3 bucket that we create
- Updates S3 bucket name to be more useful for users
Closes #111

Set default encryption on S3 bucket and update bucket name

---

pkg/resource/podtemplatespec.go

Fixes https://github.com/openshift/cluster-image-registry-operator/issues/42

Use cr.Spec.Proxy.HTTP and cr.Spec.Proxy.HTTPS

---

pkg/operator/controller.go

workqueue.AddRateLimited may start to ignore events when a burst occurs. And we don't want to delay handling of CR changes.

Always handle events from watchers

---

pkg/apis/imageregistry/v1alpha1/types.go
pkg/resource/podtemplatespec.go

Addresses comment: https://github.com/openshift/cluster-image-registry-operator/pull/116#discussion_r240661393
@bparees Please review.

Add CR.Spec.Proxy.NoProxy

---

deploy/02-rbac.yaml
pkg/clusteroperator/clusteroperator.go
pkg/testframework/imageregistry.go
test/e2e/aws_test.go
test/e2e/basic_empty_dir_test.go

fixes https://github.com/openshift/cluster-image-registry-operator/issues/75

update clusteroperator status properly and add rbac permission to do so

---

deploy/02-rbac.yaml
pkg/storage/s3/s3.go
pkg/storage/util/util.go
test/e2e/aws_test.go

This is a temporary patch until #106 merges

Use Cluster Version ClusterID instead of Install Config ClusterID

---

pkg/resource/nodecadaemon.go

@bparees @runcom ptal.
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

Add support for syncing registry certs

---

pkg/operator/bootstrap.go
pkg/resource/generator.go
pkg/storage/emptydir/emptydir.go
pkg/storage/s3/s3.go
pkg/testframework/framework.go

skip driver.CompleteConfiguration if the driver is nil

---

pkg/storage/s3/s3.go

- Do not tag the bucket if we did not create it
- Do not encrypt the bucket if we did not create it
- Do not enable cleanup of incomplete multipart uploads if we did not create the bucket
Fixes #160

Do not encrypt the bucket if we did not create it

---

pkg/clusterconfig/clusterconfig.go

Use the secret provided by the cloud credentials minter

Use cloud credentials secret

---

pkg/clusterconfig/clusterconfig.go

https://bugzilla.redhat.com/show_bug.cgi?id=1670357

better error reporting on failed secret retrieval

---

pkg/resource/imageconfig.go

https://bugzilla.redhat.com/show_bug.cgi?id=1670772

use newly created object for update invocation

---

hack/build/build.sh
pkg/apis/imageregistry/v1/register.go
pkg/client/client.go
pkg/migration/dependency/namespacedresources.go
pkg/migration/migration.go
pkg/operator/complete.go
pkg/operator/controller.go
pkg/resource/podtemplatespec.go
pkg/storage/util/util.go
test/e2e/aws_test.go

- fix bash simple variable
- comments should start with a space
- removed unused functions, parameters, and code

A few more cleanup items

---

manifests/01-registry-credentials-request.yaml

replaces https://github.com/openshift/cluster-image-registry-operator/pull/190

add credential request for aws

---

pkg/resource/nodecadaemon.go

fixes https://github.com/openshift/cluster-image-registry-operator/issues/197

update nodeca image spec if image payload changes

---

manifests/registry-config.yaml
pkg/apis/imageregistry/v1/types.go
test/e2e/aws_test.go

Renaming image registry resource from instance to cluster

Renaming image registry resource

---

manifests/00-crd.yaml
pkg/operator/controller.go

Enable subresource status

---

test/e2e/pvc_test.go

test/e2e: Do not wait for PVC to change its status from "Pending" to something else

---

pkg/clusterconfig/clusterconfig.go

https://bugzilla.redhat.com/show_bug.cgi?id=1684738
/cc @coreydaley

Fix namespace for errors for installer-cloud-credentials

---

pkg/apis/imageregistry/v1/types.go
pkg/storage/swift/swift.go

this is needed for openstack to make the registry run on swift

openstack: add domain and tenant config

---

pkg/storage/s3/s3.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1684738

Update region from the install config if not present

---

pkg/apis/imageregistry/v1/types.go
pkg/apis/imageregistry/v1/zz_generated.deepcopy.go
pkg/resource/podtemplatespec.go
test/e2e/configuration_test.go

https://jira.coreos.com/browse/DEVEXP-280

Add ability to set tolerations for registry pod

---

pkg/storage/storage.go

Do not configure PVC by default

---

pkg/resource/podtemplatespec.go

https://jira.coreos.com/browse/DEVEXP-249
@openshift/sig-developer-experience fyi
/hold  
still want to experiment with changing the replicas setting on the config object ... getting the PR up for a sanity check since I missed planning, plus get regression testing

add anti affinity to docker registry pods

---

pkg/clusteroperator/clusteroperator.go
pkg/operator/controller.go
pkg/resource/caconfig.go
pkg/resource/clusterrole.go
pkg/resource/clusterrolebinding.go
pkg/resource/deployment.go
pkg/resource/generator.go
pkg/resource/imageconfig.go
pkg/resource/nodecadaemon.go
pkg/resource/resource.go
pkg/resource/route.go
pkg/resource/secret.go
pkg/resource/service.go
pkg/resource/serviceaccount.go

Add must-gather object refs

---

pkg/storage/pvc/pvc.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1700294
/assign @dmage

Fix PVC access mode validation 

---

pkg/operator/bootstrap.go
pkg/operator/controller.go
pkg/operator/status.go
pkg/resource/clusteroperator.go
pkg/resource/generator.go
test/e2e/aws_test.go
test/e2e/baremetal_test.go
test/e2e/configuration_test.go
test/e2e/emptydir_test.go
test/e2e/pvc_test.go
test/e2e/readonly_test.go
test/framework/imageregistry.go

Fixes [BZ#1704590](https://bugzilla.redhat.com/show_bug.cgi?id=1704590)

Apply ClusterOperator even if everything is bad

---

OWNERS

* Added @gabemontero as reviewer

Remove legionus as reviewer/approver

---

pkg/resource/nodecadaemon.go

in service to https://github.com/openshift/origin/pull/22787

pkg: add resource requests to node-ca pod

---

pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

Now in gophercloud the default endpoint type for swift containers is "container", but many OpenStack clouds are deployed with a single endpoint type for all Swift entities - "object-store".
This commit adds this check, and if "container" endpoint is not found, then we'll be looking for an endpoint called "object-store".

Swift: fallback to "object-store" endpoint type

---

pkg/resource/nodecadaemon.go

ref: https://jira.coreos.com/browse/POD-114

use GA kubelet OS label

---

pkg/operator/controller.go
pkg/resource/podtemplatespec.go

https://bugzilla.redhat.com/show_bug.cgi?id=1727595
Reverts #315 and adds IsNotFound to the code that was causing the error

Bug 1727595: Fix error on proxy config not found

---

test/e2e/configuration_test.go

[release-4.1] Bug 1730407: add test for route secrets

---

pkg/storage/gcs/gcs.go

Looks like serviceaccount.json was renamed to service_account.json

change serviceaccount.json to service_account.json

---

pkg/storage/azure/azure.go

Looks like we were not watching for the correct service code so
that we could retry the container creation with a different name
https://bugzilla.redhat.com/show_bug.cgi?id=1733902

Bug 1733902: Retry container creation on correct ServiceCode

---

pkg/storage/gcs/gcs.go

No labels are needed for the bucket
Bucket name needs to start with the infrastructure name

Update GCS bucket creation

---

pkg/storage/azure/azure.go

CreateStorage was always using a static container name of "image-registry", so if you removed the container name, it would try to recreate the same container name again.  Added some randomization to the name

Bug 1737053: Fixing error 409 container name exists

---

test/e2e/configuration_test.go
test/e2e/gcs_test.go
test/framework/imageregistry.go
test/framework/proxy.go
test/framework/util.go

We should not need to set the global proxy status manually  anymore

Don't set global proxy status manually

---

pkg/resource/nodecadaemon.go
test/e2e/graceful_shutdown_test.go
test/framework/logs.go

This patch adds a trap to deal with SIGTERM, allows sleep to be
interrupted by signaling.

Bug 1710502: Using trap to deal with signaling on node-ca.

---

pkg/storage/util/util.go
pkg/storage/util/util_test.go

In some cases infrastructure contains multiple dashes in a sequence, Azure does not like it. This patch makes sure we always remove a sequence of dashes by a single one.
Tests were refactored to contains a variable infra name.
During the investigations I have seen on the must-gather for the problematic deployment that the image registry was deployed with the following environment variable:
```
Environment:
REGISTRY_STORAGE_AZURE_CONTAINER:       qewalid420825233east--rhgcq-image-registry-exmgmspubjtcamgowcr
```
Double dashes(`--`) are considered invalid for a container name: https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata
These two extra dashes were coming in from the Infrastructure name configuration.

Bug 1745811: Making sure we don't have a sequence of dashes.

---

pkg/storage/gcs/gcs.go

A future PR will address setting the operators available false, degraded true

Bug 1738475: Update condition reason code for invalid keyID

---

pkg/storage/azure/azure.go

Azure should create a custom container with name provided by user
Also fixed up a few other parts of the Azure CreateStorage flow

Bug 1740035: Azure should create custom container

---

pkg/resource/clusteroperator.go

Bug 1752916: add config resource to relatedObjects

---

test/e2e/imageconfig_test.go

When user swaps storages on image registry configuration only one should
still be enabled on Status. Added test to swap an IPI provided storage
by an EmptyDir one and checking if only EmptyDir is still set on Status.
This is a test to cover #394 , it is a nice to have even if we decide not to 
backport the fix.

Implementing test for storage swap.

---

pkg/storage/s3/s3.go

Fixes the problem from https://issues.redhat.com/browse/RFE-327?focusedCommentId=13935691&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13935691

Bug 1784208: force path style for custom endpoints

---

pkg/envvar/envvar.go
pkg/envvar/envvar_test.go
pkg/resource/podtemplatespec.go
pkg/resource/secret.go
pkg/storage/azure/azure.go
pkg/storage/emptydir/emptydir.go
pkg/storage/gcs/gcs.go
pkg/storage/pvc/pvc.go
pkg/storage/s3/s3.go
pkg/storage/storage.go
pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

Previous attempt #391.
Fixes openshift/installer#2392.

Encode environment variables as YAML

---

test/e2e/configuration_test.go
test/framework/framework.go
test/framework/proxy.go

Check for errors in defer

---

pkg/resource/object/diff.go
pkg/resource/podtemplatespec.go
pkg/storage/azure/azure.go
pkg/storage/gcs/gcs.go
pkg/storage/pvc/pvc.go

Fix some issues that are found by golangci-lint.

Fix lint warnings

---

pkg/operator/status.go
pkg/resource/generator.go

Report the image pruner's install metric when we sync status.

Report image pruner install status correctly.

---

pkg/resource/caconfig.go
pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

[release-4.3] Bug 1796822: Support deployment on OpenStack with self-signed certificate

---

pkg/storage/swift/swift.go

Fix regression after 34a535d0ea7d27d90159eb2aaa7a310258c295f0.

Bug 1785534: fix regression

---

pkg/operator/bootstrap.go
pkg/resource/generator.go
pkg/storage/storage.go

[release-4.4] Bug 1810562: bootstrap HA configuration

---

pkg/resource/nodecadaemon.go
pkg/resource/nodecadaemon_test.go

[4.3] Bug 1820242: nodeca daemon should tolerate all taints

---

pkg/operator/bootstrap.go
pkg/operator/clusteroperator.go
pkg/operator/controller.go
pkg/resource/clusteroperator.go
pkg/resource/clusteroperator_test.go
pkg/resource/generator.go
test/e2e/baremetal_test.go

[release-4.3] Bug 1816656: update ClusterOperator object even if operator is unmanaged

---

test/e2e/managementstate_test.go

Tests were flaking on this as the operator is updating the resource
while the test runs.
Error being reported during tests:
```
managementstate_test.go:149: Operation cannot be fulfilled on configs.imageregistry.operator.openshift.io "cluster": the object has been modified; please apply your changes to the latest version and try again
```

Bug 1828719: Retry updating config resource during tests.

---

pkg/operator/bootstrap.go
pkg/storage/storage.go

Bootstrap HA configuration for the image registry by default.

Bug 1810563: bootstrap HA configuration

---

Makefile

Bug 1831088: removing verify-sec / gosec

---

pkg/client/listers.go
pkg/operator/controllerimagepruner.go
pkg/resource/generator.go
pkg/resource/generatorimagepruner.go
pkg/resource/prunercronjob.go

Bug 1813894: Stop using service ca from service account token

---

test/e2e/gcs_test.go

GCS test was broken. Now it creates a bucket and tests if user provided
credentials propagate to running registry.

Bug 1834243: Refactored GCS day 2 e2e tests

---

pkg/client/fake/fixtures.go
pkg/client/listers.go
pkg/client/operatorclient.go
pkg/operator/clusteroperator.go
pkg/operator/controller.go
pkg/operator/controllerimagepruner.go
pkg/operator/imageconfig.go
pkg/operator/imageregistrycertificates.go
pkg/operator/nodecadaemon.go
pkg/operator/starter.go
pkg/operator/status.go
pkg/resource/clusteroperator.go
pkg/resource/clusteroperator_test.go
test/e2e/pruner_test.go
vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
vendor/modules.txt

The ClusterOperator objects represent the entire operator. The image registry operator has several controllers, and if one of them has a problem, the operator should report it.

Bug 1823676: Aggregate conditions from all controllers

---

pkg/storage/azure/azure.go
pkg/storage/azure/azure_test.go

This PR adds unit tests for function `GetConfig()`. As I am moving now to work on our StorageInterface and this is kinda done I thought it would be good to have this in.

Implementing unit tests for GetConfig

---

pkg/operator/bootstrap.go

When the csi driver for ovirt was merged into the storage operator[1] there is no "standard" StorageClass in the cluster, but there is a ovirt-csi-sc storage class which is the default storage class.
This cause the installer to fail due to image registry not being ready, since it was panding due to the pending pvc.
Instead the default storageclass should be used, see thread on forum-storage[2], not specifing the storage class[3] catches the default storage class.
[1] https://github.com/openshift/cluster-storage-operator/pull/65
[2] https://coreos.slack.com/archives/CBQHQFU0N/p1596452181198600
[3] https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>

BUG 1862991: Remove storageclass from PVC creation

---

pkg/storage/swift/swift.go

Currently when we destroy Swift image registry container with BulkDelete, all internal errors are ignored, which can lead to some obscure issues in the future.
This commit parses the response and returns an error if Swift failed to delete some objects.

Bug 1869613: don't ignore swift errors during container deletion

---

pkg/storage/swift/swift_test.go

This test emulates Swift behavior if it fails to delete one of the given objects in bulk mode.

Bug 1869613: Swift: add a unit test for bulk deleting failure

---

pkg/metrics/metrics.go
pkg/metrics/server.go
pkg/storage/azure/azure.go
pkg/storage/azure/azure_test.go
pkg/storage/azure/cached_key.go
pkg/storage/azure/cached_key_test.go

Reusing the same primary access key, caching it for five minutes.

Bug 1853734: Reusing Azure API key

---

pkg/operator/controller.go
pkg/operator/status.go
pkg/operator/status_test.go

This commits adds a check for route statuses during operator status sync
process. If any of the routes was not Admitted the operator will report
itself as Degraded.

Bug 1902076: Checking for route status

---

pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go
test/e2e/aws_test.go

The operator should support AWS endpoints that are provided via the cluster infrastructure resource.

Bug 1939842: Get AWS STS endpoint from serviceEndpoints

---

pkg/resource/podtemplatespec.go

The registry should give endpoints time to propagate through the system. Otherwise requests will go to the pod that is shutting down.
See also:
* https://learnk8s.io/graceful-shutdown
* https://github.com/openshift/console-operator/commit/8010dd8093f8eb120fce1208fdd55eab69891558

Bug 1972827: Avoid disruptions

---

pkg/operator/clusteroperator.go
pkg/operator/controller.go
pkg/operator/controllerimagepruner.go
pkg/operator/imageconfig.go
pkg/operator/imageregistrycertificates.go
pkg/operator/nodecadaemon.go

These messages are not meaningful for customers and rarely used even for debugging.

Bug 1907433: Decrease severity for event queue messages

---

docs/development-build.md
hack/add-cvo-overrides.sh

the group on each item should not contain v1.

hack: fix CVO overrides

---

.ci-operator.yaml
Dockerfile
tools.go

Use go 1.17

---

go.mod

Merge all `require` blocks and format they with `go mod tidy`.

Cleanup go.mod

---

manifests/09-prometheus-rules.yaml

Removing alters that happens only after administrators actions.

Bug 1992553: Remove PrometheusRule

---

pkg/resource/podtemplatespec.go

When the registry pod cannot reach its storage, it should report about problems.

Bug 2015459: Enable health check for storage driver

---

docs/README.md
docs/metrics.md
manifests/09-prometheus-rules-imagestreams.yaml
manifests/09-prometheus-rules-registry-operations.yaml

Bug 2009352: IR-253: add prometheus rules for image registry operations metrics

---

pkg/resource/podtemplatespec_test.go
pkg/storage/s3/s3.go

Bug 2084514: Fix cloudfront middleware configuration

---

OWNERS

add myself to OWNERS

---

pkg/storage/ibmcos/ibmcos.go

OCPBUGS-6797: Add nil validation for IBM Cloud and Power VS infrastructure status in ibmcos

---

.github/dependabot.yml

this way they will get bumped together in the same PR.

.github/dependabot.yml: group certain dependencies

---

manifests/01-registry-credentials-request-gcs.yaml

This reverts commit 4799b360c6d8aeb23bd8f56b76a1bea041576d69, reversing changes made to 06dfe471e15f6a54640b363747fd45afa5111052.

TRT-1368: Revert "Merge pull request #935 from flavianmissi/CCO-248"

---

manifests/01-registry-credentials-request-gcs.yaml

This reverts commit ab48b08e70fce2b671c497d09d6d443f0e7e1227, reversing changes made to 0c6fdc34f198e33e46c6c8da61c626f81f0e8e97.

CCO-248: Revert "Merge pull request #965 from jstuever/TRT-1368"

---

OWNERS

no longer makes sense for me to have approval rights here (probably hasn't for a while).

NO-JIRA: remove bparees from owners

---

pkg/resource/azurepathfixjob.go

OCPBUGS-33149: azure-path-fix: get client secret from k8s secret

---

manifests/02-rbac.yaml

/cc @flavianmissi 
Required by https://github.com/openshift/hypershift/pull/4123

OCPBUGS-34399: Update rbac for featuregate

---

pkg/storage/s3/s3.go

IR-471: Adding additional validation

---

pkg/storage/azure/azure.go
pkg/storage/azure/azureclient/azureclient.go

This PR enables Azure MSI authentication, which will be utilized in the managed service - ARO HCP.
Fixes [IR-467](https://issues.redhat.com/browse/IR-467)

IR-467: Enable Azure MSI authentication

---

pkg/storage/azure/azure.go
pkg/storage/azure/azureclient/azureclient.go

Reverts openshift/cluster-image-registry-operator#1020

Revert "IR-467: Enable Azure MSI authentication"

---

pkg/storage/azure/azure.go
pkg/storage/azure/azureclient/azureclient.go

ARO HCP needs to force the Azure authentication type to MSI for deployments of the cluster-image-registry in ARO HCP control planes. See https://docs.google.com/document/d/1Z7N2LAnRlgSgrFjjl2absOnkGFsI2TMcbwaW_CA1qek/edit#heading=h.bupciudrwmna for more details.

IR-467: Enable MSI override for ARO HCP

---

pkg/storage/azure/azure.go
pkg/storage/azure/azureclient/azureclient.go

This commit changes image registry to look for a stored Azure credential to reuse to authenticate with Azure. If there is no stored Azure credential, authenticate to Azure with UAMI and store the credentials.
Prior to this commit, image registry was getting new credentials every continually; this led to an issue where image registry would open too many filewatchers as NewUserAssignedIdentityCredential opens a new filewatcher on every call.

CNTRLPLANE-112: Authenticate to Azure only once in CPO

---

.ci-operator.yaml
Dockerfile
Makefile
pkg/operator/status.go

Trying to fix the verify job on https://github.com/openshift/cluster-image-registry-operator/pull/1165

OCPBUGS-45409: Updating ose-cluster-image-registry-operator-container image to be consistent with ART for 4.19

---

pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

Previously, authentication with Swift supported application credentials, username/password or the legacy ApiKey. This commit adds support for authenticating using Keystone v3token.

OSASINFRA-3756: Add support for token-based authentication in clouds.yaml configuration file
