deploy/cr.yaml

`imageregistries.imageregistry.operator.openshift.io` CRD is Namespaced.
But the cr.yaml doesn't have namespace setup. Cluster Version Operator
will not have context to decide which namespace the CR shouldbe installed in.

deploy: add namespace for the CR.

---

pkg/clusterconfig/clusterconfig.go

This may be why some operator runs are [dying with][1] (although I haven't read through #54 yet):
```
time=""2018-11-05T19:42:08Z"" level=info msg=""Cluster Image Registry Operator Version: 601f5c3-dirty""
time=""2018-11-05T19:42:08Z"" level=info msg=""Go Version: go1.10.3""
time=""2018-11-05T19:42:08Z"" level=info msg=""Go OS/Arch: linux/amd64""
time=""2018-11-05T19:42:08Z"" level=info msg=""operator-sdk Version: 0.0.6+git""
time=""2018-11-05T19:42:08Z"" level=info msg=""Metrics service cluster-image-registry-operator created""
time=""2018-11-05T19:42:08Z"" level=info msg=""generating registry custom resource""
time=""2018-11-05T19:42:08Z"" level=fatal msg=""unknown storage backend: """
```
When returning a potentially-troublesome, empty configuration with a `nil` error, we should at …

pkg/clusterconfig: Log missing config-map

---

Dockerfile
Dockerfile.rhel7
deploy/05-ca-config.yaml
deploy/06-ca-rbac.yaml
deploy/07-ca-serviceaccount.yaml
deploy/08-ca-daemonset.yaml

This is a temporary hack to ensure the service-ca (which signs the registry service) gets copied to the host nodes.
In the future this needs to be replaced/enhanced in such a way that 
1) it needs less privileges(probably)
2) ~~should use the base image from the release, not centos~~
3) the image-registry operator reports on the state of the daemonset as part of the registry operator status
4) we also copy down additional CAs that are configured in the cluster that represent other registries the nodes may need to pull from.  (ie image.config.openshift.io's additionalCA configmap)

add temporary hack to copy service ca to cluster nodes

---

pkg/storage/s3/s3.go
test/e2e/aws_test.go

- Set installConfig.Platform.AWS.UserTags as tags on the created S3 bucket

Set user tags on s3 bucket

---

cmd/cluster-image-registry-operator/main.go
pkg/operator/bootstrap.go
pkg/operator/controller.go
pkg/operator/controller/clusterrolebindings/clusterrolebindings.go
pkg/operator/controller/clusterroles/clusterroles.go
pkg/operator/controller/configmaps/configmap.go
pkg/operator/controller/deployments/deployment.go
pkg/operator/controller/imageregistry/imageregistry.go
pkg/operator/controller/routes/routes.go
pkg/operator/controller/secrets/secret.go
pkg/operator/controller/serviceaccounts/serviceaccounts.go
pkg/operator/controller/services/service.go
pkg/operator/finalizer.go
pkg/operator/status.go
pkg/resource/generator.go
pkg/storage/storage.go
pkg/storage/util/util.go

After discussion with Master team, we came to the conclusion that for
now you need to roll back to glog and wait for kubernetes-1.13 where it
is likely to switch to klog.
But we need to be careful, since messages from modules that use klog
will be lost now and we have no protection against this.
Fixes github.com/openshift/cluster-image-registry-operator/issues/85

Rollback from k8s.io/klog to github.com/golang/glog

---

cmd/cluster-image-registry-operator/main.go
pkg/clusterconfig/clusterconfig.go
pkg/operator/controller.go
pkg/operator/controller/imageregistry/imageregistry.go
pkg/operator/controller/routes/routes.go
pkg/storage/util/util.go
test/e2e/aws_test.go

Cleaning up a few items that I noticed during previous work:
- guard against Platform.AWS being nil
- error string should not start with a capital letter
- variable should not mask imported package name
All are in their own commits for easy review

A few cleanup items

---

pkg/storage/s3/s3.go
test/e2e/aws_test.go

The tectonicClusterID tag is being replaced with openshiftClusterID in the installer. This change will use the new tag name.
Hold on openshift/installer#817.
/hold

replace tectonicClusterID tag with openshiftClusterID

---

pkg/storage/s3/s3.go

The tectonicClusterID tag was replaced with openshiftClusterID in 63442f4f5ee14287345f1e4d8129197d8b4450e6. However, there was a comment inadvertently left behind that still references tectonicClusterID.
See #114.

fix comment that still refers to tectonicClusterID

---

pkg/clusterconfig/clusterconfig.go
pkg/operator/controller.go
pkg/resource/strategy/override_test.go
pkg/storage/gcs/gcs.go
pkg/storage/s3/s3.go

Fixing a few small issues that I have run across:
- Update deprecated ImageRegistry() with ImageRegistryV1alpha1()
- Use snake case instead of CAMEL_CASE
- fix using %q when we shouldn't be
- variable name masks imported package name (and package was imported twice"
Each in it's own commit for easy review.

A few small cleanup items

---

pkg/apis/imageregistry/v1alpha1/types.go
pkg/storage/s3/s3.go
test/e2e/aws_test.go

- Delete the leftover parts of an incomplete multipart upload
- Refactor a few small sections of the s3 driver file (no functionality changes)
Fixes #128

Abort incomplete multipart uploads on AWS/S3

---

pkg/clusterconfig/clusterconfig.go
pkg/operator/finalizer.go
pkg/resource/generator.go
pkg/storage/s3/s3.go
pkg/storage/util/util.go
test/e2e/aws_test.go
test/e2e/util.go

- variable name should not mask imported package name
- errors should not start with a capital letter or end with punctuation
- update to new function name (previous was deprecated)
- refactor storage finalizer to retry on conflict with a new version of the image registry resource and update the test for the s3 finalizer

a small refactor / cleanup

---

pkg/operator/bootstrap.go
pkg/operator/finalizer.go
pkg/resource/caconfig.go
pkg/resource/generator.go
pkg/storage/azure/azure.go
pkg/storage/emptydir/emptydir.go
pkg/storage/filesystem/filesystem.go
pkg/storage/gcs/gcs.go
pkg/storage/s3/s3.go
pkg/storage/storage.go
pkg/storage/swift/swift.go
pkg/storage/util/util.go
test/e2e/aws_test.go

setting "modified=true" everytime we ran syncStorage meant we kept triggering ourselves infinitely.
(we'd update the CR, which would result in an event, which would call syncStorage, which would set modified=true which meant we'd update the CR, and repeat).
Another way to avoid this would be to diff the new/old object and ignore the event if the only change is the resourceVersion, but I think this is the "right" way to solve it.

be more judicious when setting modified=true

---

pkg/resource/nodecadaemon.go

Fixes #138 
@bparees @derekwaynecarr ptal
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

Make the node CA daemonset only run on Linux using a nodeselector

---

pkg/operator/controller.go
pkg/operator/finalizer.go
pkg/resource/generator.go
pkg/storage/azure/azure.go
pkg/storage/emptydir/emptydir.go
pkg/storage/filesystem/filesystem.go
pkg/storage/gcs/gcs.go
pkg/storage/s3/s3.go
pkg/storage/storage.go
pkg/storage/swift/swift.go
pkg/util/util.go
test/e2e/aws_test.go

Remove the storage medium (if we manage it):
- When the finalizer runs
- When the ManagementState is set to Removed
Also moved objectInfo to pkg/util/util.go (ObjectInfo) so that it can easily be used in more places.

Remove storage medium if ManagementState set to Removed

---

pkg/apis/imageregistry/v1/types.go
pkg/operator/complete.go
pkg/resource/generator.go
pkg/resource/imageconfig.go
pkg/testframework/clientset.go
test/e2e/configuration_test.go

Set the external registry hostname in the cluster configuration (this drives the imagestream public docker repository value) when routes are configured for the registry.

set external registry hostnames on cluster image config

---

deploy/00-crd.yaml

The CRD is now managed by [cluster-config-operator](https://github.com/openshift/cluster-config-operator/blob/master/manifests/0000_05_config-operator_01_image.crd.yaml).

Remove CRD for images.config.openshift.io

---

pkg/operator/bootstrap.go
pkg/operator/controller.go

The bootstrap process only needs to look for a single custom resource, not a list.

Refactoring bootstrap.go to only look for one custom resource

---

test/e2e/configuration_test.go

fixes https://github.com/openshift/cluster-image-registry-operator/issues/206

check deployment memory, not pod to avoid looking at a stale pod

---

pkg/storage/storage.go

This commit adds OpenStack as a supported platform using an empty dir.
Note that this is not production ready and it's being done as a way to
allow OpenStack based deployments to succeed and move on.
Eventually this should be switched to swift.

openstack: Add temporary OpenStack suport on FS

---

Makefile
pkg/resource/caconfig.go
pkg/resource/clusterrole.go
pkg/resource/clusterrolebinding.go
pkg/resource/deployment.go
pkg/resource/generator.go
pkg/resource/imageconfig.go
pkg/resource/nodecadaemon.go
pkg/resource/resource.go
pkg/resource/route.go
pkg/resource/secret.go
pkg/resource/service.go
pkg/resource/serviceaccount.go
pkg/storage/pvc/pvc.go

fixes https://github.com/openshift/cluster-image-registry-operator/issues/216

do not setup ownerrefs for clusterscoped/cross-namespace objects

---

pkg/storage/s3/s3.go

An example of version infromation in UserAgent is `terraform-provider-aws` [1]
[1]: https://github.com/terraform-providers/terraform-provider-aws/blob/98f11aecb078d82fd7d9b59e5307874797d8f359/aws/config.go#L420

s3: include operator version in UserAgent for AWS API calls

---

pkg/resource/podtemplatespec.go

specifies system-cluster-critical priority for operands that run on masters.
blocks passing smoke tests for ensuring control plane pods always schedule.
see: openshift/origin#22217

resource: specify system-cluster-critical priority for registry

---

manifests/07-operator.yaml

operator should use IfNotPresent image pull policy
see: https://github.com/openshift/origin/pull/22230

manifests: update image pull policy

---

pkg/storage/s3/s3.go

Currently it is not possible to change the s3 storage to another region by setting the RegionEndpoint. This PR will fix that issue.

add missing s3 endpoint

---

test/e2e/aws_test.go

This test has passed multiple times for me locally running by itself and as part of the test suite.
Fixes #221

Re-enable TestAWSUnableToCreateBucketOnStartup

---

manifests/01-registry-credentials-request.yaml

in order to avoid the CVO periodically applying v1beta1 and then having the cloud-cred-operator migrate it to v1 (see https://bugzilla.redhat.com/show_bug.cgi?id=1690069 ), just update the credentialsrequest in the manifests dir to v1 (no changes from v1beta1 to v1)

update credentialsrequest from v1beta1 to v1

---

manifests/01-namespace.yaml
manifests/01-openshift-config-managed-namespace.yaml
manifests/01-openshift-config-namespace.yaml

**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …

Add node-selector annotation to namespace

---

manifests/07-operator.yaml

In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …

Fix tolerations

---

README.md
pkg/clusterconfig/clusterconfig.go
pkg/storage/gcs/gcs.go
test/e2e/gcs_test.go

- Change STORAGE_GCS_KEYFILE -> REGISTRY_STORAGE_GCS_KEYFILE
- Add REGISTRY_STORAGE_GCS_KEYFILE to README for the ImageRegistryPrivateConfigurationUser secret
- Remove -n openshift-image-registry from oc get of cluster scoped resources in README

Updates to the GCS configuration and documentation

---

pkg/storage/storage.go

Swift storage needs cloud-credential-operator support to obtain system credentials. Until it's done we'll use EmptyDir for OpenStack deployment.

Temporarily switch OpenStack to EmptyDir

---

pkg/storage/storage.go

Now cloud-credential-operator has OpenStack support, so we can enable Swift again.
This reverts #285

Revert "Temporarily switch OpenStack to EmptyDir"

---

cmd/cluster-image-registry-operator/main.go
pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

This patch prevents the same container name from being generated.

OpenStack: generate different container names

---

manifests/00-crd.yaml
pkg/apis/imageregistry/v1/types.go
pkg/clusterconfig/clusterconfig.go
pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

Docker registry uses ncw/swift library to interact with Swift, which determines Auth Version from the Auth URL:
https://github.com/ncw/swift/blob/24e3012fc8a71f004a6455bce2088031d50bf2b6/auth.go#L56-L65.
But since Keystone supports autodetection, often this parameter is not present in the URL, and because of this the code above fails with 500.
This patch allows to specify auth version in the config, and defaults it to 3, which is the only supported version.
It is also important from the viewpoint of stability because that code in ncw/swift simply checks for the presence of a substring in the Auth URL. It means that with AuthURL https://zxcv1.com/ v1 authentication will be used, which is wrong.

OpenStack: allow to explicitly specify keystone auth version

---

manifests/01-registry-credentials-request.yaml
pkg/apis/imageregistry/v1/types.go
pkg/storage/s3/s3.go
test/e2e/aws_test.go

Blocks public access to the S3 bucket that we create and the objects that it contains along with tests to verify
https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html

Block public access to S3 bucket and its objects by default

---

pkg/operator/controller.go

https://bugzilla.redhat.com/show_bug.cgi?id=1727595

Bug 1727595: Warn on missing proxy config instead of error

---

hack/build/build.sh

This change is necessary to allow building on other architectures.

Do not hardcode GOOS/GOARCH

---

pkg/client/clients.go
pkg/operator/controller.go
pkg/resource/generator.go

Refactor client creation/usage between the controller and the generator
to reuse already created clients instead of creating so many new ones

Refactor client creation/usage

---

pkg/storage/s3/s3.go

The s3 bucket needs to be emptied of all objects before it can
be deleted, not doing so will cause the finalizer to hang.

Bug 1737526: Empty s3 bucket before deleting

---

pkg/storage/s3/s3.go

Without this tag the resource won't be destroyed by Terraform

Add Name tag to S3 bucket

---

pkg/storage/s3/s3.go

If the operator is creating storage for the registry, the name of the storage medium should be prefixed with the cluster name

Start storage name with cluster name

---

pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

This commit adds metadata to the generated Swift image registry container to allow Terraform to delete it at the time the cluster is destroyed.
Also it changes the format of container naming in Swift:
<clusterID>-image-registry-<8_random_letters>, which is common for all resources created by Terraform.
Fixes: #317

OpenStack: set container metadata

---

pkg/resource/podtemplatespec.go
test/e2e/configuration_test.go

Image registry expects REGISTRY_OPENSHIFT_REQUESTS_READ_MAXWAITINQUEUE
and REGISTRY_OPENSHIFT_REQUESTS_WRITE_MAXWAITINQUEUE to be of type
time.Duration. This patch renders only the Duration property of a metav1.Duration
struct.

Bug 1726894: Properly setting "maxWaitTime" environment var.

---

manifests/04-ca-config.yaml
test/e2e/aws_test.go
test/framework/configmap.go
test/framework/daemonset.go

The serviceca ConfigMap is used by operand components.
CVO should not be responsible for creating it or managing its content.

Bug 1734564: Remove Service CA ConfigMap from CVO management

---

pkg/storage/gcs/gcs.go

Panic caused by bucket being nil if it already exists and doesn't
need to be created

Bug 1738475: Bucket is nil if already exists during update

---

pkg/storage/azure/azure.go
pkg/storage/gcs/gcs.go
pkg/storage/s3/s3.go
pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go
pkg/storage/util/util.go
pkg/storage/util/util_test.go

- Use a commont generateName function to generate storage name
- Wrap the swift storage creation in a loop that checks for an existing container
- Swift test fixes donated by @Fedosin, thanks!
Fixes #358

Use common generateName for storage

---

manifests/01-registry-credentials-request-azure.yaml

After cloud credential operator starts supporting resource group
scoped credential minting for Azure, all CCO will be required to set
at least one role in role bindings. If a CCO failed to do so,
no secret with azure credential will be minted.
Contributor role permissions should be sufficient. If not, please extend the list of role bindings with additional roles.
PR adding the support for resource group scoped credentials: https://github.com/openshift/cloud-credential-operator/pull/95

Set default role for minted credentials to Contributor

---

manifests/04-ca-trusted.yaml
manifests/07-operator.yaml

Injects the cluster proxy CA into `/etc/pki/ca-trust/source/ca-bundle.crt`

DEVEXP-403: Mount cluster trusted CA to image registry operator

---

manifests/07-operator.yaml

We don't need to mount the same volume on the watcher, as long as it is
mounted on the operator we are ok as the watcher does not monitor the
file directly but a link from /proc/_operator-pid_/root/... instead.

Removed CA volume mount from watch container.

---

pkg/client/fake/fixtures.go
pkg/operator/controller.go
pkg/parameters/parameters.go
pkg/resource/podtemplatespec.go
pkg/resource/podtemplatespec_test.go

Ensures that no other base trust is present for the registry.

DEVEXP-402: Mount trusted-ca to registry base pki trust source

---

Dockerfile

Watcher, on library-go, reports the same binary name when using symlink
as it searchs for the executable name by looking at /proc/pid/exe link.
/proc/pid/exe points to the same destination as the symlink points to,
this causes both process to have the same "name".

DEVEXP-403: Using hard link when creating watcher binary.

---

Dockerfile
images/bin/entrypoint.sh
manifests/07-operator.yaml

* Mount cluster trust bundle in non-system location
* Added entrypoint to copy trust bundle
* Updated perms of /etc/pki/ca-trust/extracted files to allow overwrites
Builds on #376

Overwrite CA trust bundle only on 4.2 clusters

---

manifests/07-operator.yaml

Undo mounting of the cluster trusted CA so that we unblock upgrade.

Bug 1746155: Revert mount of trusted CA bundle

---

pkg/resource/clusteroperator.go
test/framework/imageregistry.go

Ensure that `openshift-image-registry` namespace is always referenced as a related object for must-gather.

Bug 1748436: Add namespace to related objects

---

hack/build/build.sh

Similarly to openshift/console#2353, cluster-image-registry-operator has
`CGO_ENABLED=0` passed to `go build`. This is most likely a leftover
from time when image was based on alpine. As this is no longer the case,
this commit removes it.
The context of this change is a try to enable kuryr-kubernetes as SDN
for OpenShift clusters. To do so, DNS resolvers of pods running on the
cluster should support `use-vc` option in `resolv.conf`. `CGO_ENABLED=0`
forces usage of golang's internal implementation of a resolver that
doesn't support that option until golang 1.13. Removing it will make
image-registry-operator use libc resolver, which is honoring the option
and make sure that underlying OpenStack cloud URL is resolved correctly.
Deeper context of this is that OpenStack Octavia in version …

Remove CGO_ENABLED=0 from build script

---

pkg/resource/generator.go
pkg/storage/azure/azure.go
pkg/storage/emptydir/emptydir.go
pkg/storage/gcs/gcs.go
pkg/storage/pvc/pvc.go
pkg/storage/s3/s3.go
pkg/storage/storage.go
pkg/storage/swift/swift.go

When migrating from one storage to another configs/cluster Status ended up
showing multiple storage configurations, for example:
```
status:
storage:
emptyDir: {}
s3:
bucket: rmarasch-cluster-66-575tx-image-registry-us-east-1-porcoxpfplu
encrypt: true
keyID: ""
region: us-east-1
regionEndpoint: ""
```
This patch resets Storage property before running any DeepCopy(), making
sure that if the storage is changed to another media we will update
correctly.

Bug 1722878: reseting configured storages before DeepCopy()

---

cmd/cluster-image-registry-operator/main.go
manifests/0000_90_cluster-image-registry-operator_02_operator-servicemonitor.yaml
manifests/07-operator-service.yaml
manifests/07-operator.yaml
manifests/09-prometheus-rules.yaml
pkg/metrics/metrics.go
pkg/metrics/server.go
pkg/metrics/server_test.go
pkg/operator/status.go
pkg/resource/generator.go
pkg/storage/azure/azure.go
pkg/storage/emptydir/emptydir.go
pkg/storage/gcs/gcs.go
pkg/storage/pvc/pvc.go
pkg/storage/s3/s3.go
pkg/storage/storage.go
pkg/storage/swift/swift.go

This commits adds a Prometheus endpoint, exposing three metrics
indicating the following:
- Wether we have storage backend configured for the registry.
- How many times we had to change the storage backend(buckets and such).
- If we are in Degraded mode.
Metric for Degraded does not consider the lack of storage backend
configuration.
Rules for alerting are also created by this commit.

DEVEXP-404: Added implementation for operator metrics/alerts.

---

pkg/resource/generator.go
pkg/storage/azure/azure.go
pkg/storage/emptydir/emptydir.go
pkg/storage/gcs/gcs.go
pkg/storage/pvc/pvc.go
pkg/storage/s3/s3.go
pkg/storage/storage.go
pkg/storage/swift/swift.go
test/e2e/imageconfig_test.go

When migrating from one storage to another configs/cluster Status ended up showing multiple storage configurations, for example:
```
status:
storage:
emptyDir: {}
s3:
bucket: rmarasch-cluster-66-575tx-image-registry-us-east-1-porcoxpfplu
encrypt: true
keyID: ""
region: us-east-1
regionEndpoint: ""
```
This patch resets Storage property before running any DeepCopy(), making sure that if the storage is changed to another media we will update correctly.

[4.2] Bug 1759159: Reset storage when swapping back end type

---

Makefile
manifests/09-prometheus-rules.yaml
pkg/operator/bootstrap.go
pkg/resource/clusteroperator.go
pkg/resource/generator.go
pkg/storage/storage.go
test/e2e/baremetal_test.go
test/e2e/managementstate_test.go

If we detect that the platform we are bootstrapping on is bare metal we
set management state to "Removed". We still report ourselves as "Available"
but with "Reason" set to "Removed".

DEVEXP-419: Bootstrapping operator as Removed on BareMetal.

---

pkg/resource/clusteroperator.go
pkg/resource/clusteroperator_test.go

This patch uses the environment variable RELEASE_VERSION to set Operator
version if ManagementState is not "Managed". This is introduced now as we
may, in some situations, bootstrap the Image Registry Operator with Removed
ManagementState.

Bug 1753778: Set Version on Operator status even if Removed.

---

manifests/00-crd.yaml
pkg/apis/imageregistry/v1/types.go

Added pattern, min and max length for a valid Azure container name.
According to Azure documentation, "a container name must be a valid DNS name, conforming to the following naming rules":
1. Container names must start with a letter or number, and can contain only letters, numbers, and the dash (-) character.
2. Every dash (-) character must be immediately preceded and followed by a letter or number; consecutive dashes are not permitted in container names.
3. All letters in a container name must be lowercase.
4. Container names must be from 3 through 63 characters long.
https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata

Bug 1750675: Validating Azure container name.

---

pkg/resource/nodecadaemon.go
pkg/resource/nodecadaemon_test.go

Bug 1785115: tolerate all NoSchedule taints

---

pkg/operator/bootstrap.go
pkg/resource/deployment.go
test/e2e/configuration_test.go

This parameter allows to define rollout strategy for the image registry deployment.
Now support two possible rollout strategies: RollingUpdate (default) and Recreate.
The parameter was introduced by https://github.com/openshift/api/pull/560

Start using rolloutStrategy parameter

---

pkg/storage/pvc/pvc.go
test/e2e/pvc_test.go

We allow using RWO PV backend, but it has some limitations:
1. Image registry rollout strategy must be set to Recreate (default is RollingUpdate).
2. It's not possible to use more than 1 replica of the image registry.

DEVEXP-523: Allow to use RWO access mode for PVC storage type

---

defaults/defaults.go
pkg/operator/bootstrap.go
pkg/storage/pvc/pvc.go
pkg/storage/storage.go
pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

This PR allows to use RWO PVC backend for OpenStack if Swift service is not available.

Swiftless OpenStack

---

manifests/09-prometheus-rules.yaml
pkg/metrics/metrics.go
pkg/metrics/server.go
pkg/metrics/server_test.go
pkg/resource/generator.go

* Add a new Gauge metric which reports the installation status of the
automatic impage pruner.
* Alert if the image pruner is not installed and enabled
* TEMP: report that the image pruner has been installed for CI to pass

DEVEXP-433: Report image pruner's install status in Prometheus

---

pkg/resource/caconfig.go
pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

In the case where OpenStack in deployed with self-signed certificates, we need to initiate the connection to swift using a custom CA certificate.
Let's look for the `ca-bundle.pem` entry in the `openshift-config/cloud-provider-config` config map and use it to initiate the connection if it is provided.
Related to https://github.com/openshift/installer/pull/2932

Add support for OpenStack clouds with self-signed certificates

---

pkg/operator/clusteroperator.go
test/e2e/baremetal_test.go

An ErrStorageNotConfigured should not block us from creating the
ClusterOperator resource.

Bug 1803970: Creating ClusterOperator resource on ErrStorageNotConfigured

---

defaults/defaults.go
pkg/resource/generator.go
pkg/resource/podtemplatespec.go
pkg/resource/podtemplatespec_test.go
pkg/resource/pullsecret.go

This PRs creates a Mutator that migrates installation pull secrets from
openshift-config namespace into registry's namespace. It also mounts
these pull secrets so we can later on leverage them when doing image
pull throughs.

DEVEXP-515 - Mounting install pull secrets on image registry.

---

pkg/client/fake/fixtures.go
pkg/client/listers.go
pkg/operator/bootstrap.go
pkg/operator/controller.go
pkg/storage/azure/azure.go
pkg/storage/gcs/gcs.go
pkg/storage/s3/s3.go
pkg/storage/storage.go
pkg/storage/swift/swift.go
pkg/storage/util/util.go
test/e2e/aws_test.go
test/e2e/gcs_test.go
test/framework/mock/listers/listers.go

We should no longer rely on the installConfig configmap in the kubesystem.
Removing the watch for the kubesystem configmaps will fix the out of control
event processing every 4 seconds

Bug 1776665: Remove watch for KubeSystem ConfigMaps

---

pkg/operator/controller.go
pkg/operator/status.go
pkg/resource/caconfig.go
pkg/resource/clusterrole.go
pkg/resource/clusterrolebinding.go
pkg/resource/deployment.go
pkg/resource/generator.go
pkg/resource/secret.go
pkg/resource/service.go
pkg/resource/serviceaccount.go

This patch is needed as when the image registry is Removed in an environment where there is no storage backend the operator keeps logging:
"controller.go:353] unable to sync: unable to get generators: storage backend not configured, requeuing"
During removal the driver property in some Mutators is optional. This PR makes the Mutators to work without them, returning error when they are mandatory.

Bug 1798618: Make driver on Mutators optional.

---

pkg/resource/deployment.go
pkg/resource/generator.go
pkg/resource/secret.go

Making storage drivers optional on Mutator allows us to the latter when
deleting resources.
This is a stripped down version of:
9869211040b8a038a85f85802d5cf858371b58cb
The original commit contains refactoring that is not needed on a
backport, by doing so we avoid a merge conflict against 4.4 release.

Bug 1809467: Making storage driver optional on Mutators.

---

pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

Now if Swift is available for OpenStack cloud, but the user doesn't have the `swiftoperator` role, installation fails with either 403 or 401 error code from Swift, depending on its configuration.
To prevent this we check if the user has this role, and if it's not the case we fallback to RWO PVC backend.

Bug 1806158: Ignore Swift backend if the user doesn't have required permissions

---

pkg/operator/status.go
test/e2e/aws_test.go
test/e2e/baremetal_test.go
test/e2e/configuration_test.go
test/e2e/emptydir_test.go
test/e2e/failing_test.go
test/e2e/gcs_test.go
test/e2e/graceful_shutdown_test.go
test/e2e/imageconfig_test.go
test/e2e/main_test.go
test/e2e/managementstate_test.go
test/e2e/nodecadaemon_test.go
test/e2e/pruner_test.go
test/e2e/pvc_test.go
test/e2e/readonly_test.go
test/e2e/recreate_deployment_test.go
test/framework/condition.go
test/framework/configmap.go
test/framework/cvo.go
test/framework/daemonset.go
test/framework/envvars.go
test/framework/hostname.go
test/framework/imageregistry.go
test/framework/intrastructure.go
test/framework/jsonpatch.go
test/framework/operator.go
test/framework/proxy.go
test/framework/route.go
test/framework/testenv.go
test/framework/util.go

This PR introduces `framework.TestEnv`, a context for test functions.
It carries clients and testing.T, eventually we may want it to implement the context.Context interface. It is supposed to be the first argument of almost every function in the package test/framework. Any function with this context can fail the test (using te.Errorf or te.Fatalf), log additional information (te.Logf), and use k8s/okd clients.
The main idea of this PR is to make our tests more declarative. We usually don't have a fancy error handlers in our e2e tests, they usually look like this:
```
if err != nil {
return err
}
...
if err != nil {
t.Fatal(err)
}
```
It's an anti-pattern for the regular code, errors should be handled more carefully and the code should add more context details before returning the error. …

TestEnv wrapper around testing.T

---

go.mod
test/e2e/pvc_test.go

Allows for multiple consecutive executions of the same test.

Using random name for PVC during tests

---

test/e2e/graceful_shutdown_test.go
test/framework/daemonset.go
test/framework/logs.go

Graceful shutdown tests now attempt to attach to any available pod before failing.
This should mitigate the problem we are seeing during node-ca GracefulShutdown tests..

Bug 1809245: Try to attach to all pods during test

---

test/e2e/configuration_test.go
test/framework/cvo.go
test/framework/deployment.go
test/framework/imageregistry.go
test/framework/operator.go

This should fix flakes when proxy environments leak into another test.
For example in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/507/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-operator/2524, TestImageRegistryGracefulShutdown:
```
- lastTransitionTime: "2020-04-01T13:58:46Z"
message: |-
RequestError: send request failed
caused by: Head https://ci-op-h5fdww49-12abb-grk4s-image-registry-us-west-2-vyoknhwswx.s3.dualstack.us-west-2.amazonaws.com/: proxyconnect tcp: dial tcp: lookup https.example.org on 172.30.0.10:53: no such host
reason: Unknown Error Occurred
status: Unknown
type: StorageExists
```

Wait until operator is rolled out after its deployment is changed

---

pkg/storage/azure/azure.go

This should help administrators understand what the account is created for.

Prefix Azure storage account name with "imageregistry"

---

bindata/nodecadaemon.yaml
pkg/assets/bindata.go

The node-ca daemon is expected to run on all nodes soon after start
and has no need of pod network access. This causes a large number
of NetworkNotReady events to be sent and is unnecessary - the pod
should start as soon as the node is up.

bindata: Run node-ca as hostNetwork to avoid NetworkNotReady

---

pkg/storage/util/util.go
pkg/storage/util/util_test.go

Make sure we always use lower case when creating bucket names.

Bug 1827807: Assure storage bucket names in lowercase

---

test/e2e/pruner_test.go

```
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 1557 [running]:
testing.tRunner.func1(0xc000291500)
/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x19541e0, 0xc00073c920)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/openshift/cluster-image-registry-operator/test/e2e.TestPruneRegistryFlag(0xc000291500)
/go/src/github.com/openshift/cluster-image-registry-operator/test/e2e/pruner_test.go:55 +0xafc
testing.tRunner(0xc000291500, 0x1b43d50)
/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
/usr/local/go/src/testing/testing.go:960 +0x350
FAIL	github.com/openshift/cluster-image-registry-operator/test/e2e	1384.405s
```

Bug 1829910: fail the test when required objects are not found

---

pkg/resource/podtemplatespec.go

This assures we only run the operator and the operand on linux nodes.

Bug 1809005: Always set node selector kubernetes.io/os to linux

---

pkg/operator/status.go

ClusterOperator condition messages should be correct sentences.

Bug 1700206: Use sentence case for error messages

---

pkg/storage/azure/azure.go
test/e2e/configuration_test.go
test/framework/imageregistry.go

The operator's workqueue already have a retry logic, additional retries on the client side makes the operator actions less clear.

Bug 1817119: Remove retries from azure client

---

pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go

virtualHostedStyle is used only when regionEndpoint is set. The common
case is to have region without regionEndpoint, and in this case we
should bootstrap the same configuration as the previous versions did.

Bug 1838977: virtualHostedStyle should be false for public regions

---

pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go

The operator should update the S3 region configuration only when both region and regionEndpoint are unset.

Bug 1838960: Change region parameters only when region is not configured

---

manifests/09-prometheus-rules.yaml

Dear reviewer
In the past we have decided do bootstrap the registry as removed in some platforms, around the same time we also added an alert to notify the administrator if the registry was removed. Now we are having problems with some CI setup on VSphere(see related BZ) because the registry is bootstrapping as removed therefore this alarm is being triggered.
This PR removes this alert completely. Another option would be to postpone it to be triggered only a few hours later, please keep that in mind when reviewing this.
I have opted for removing this as the Registry being in a removed state is a "normal" situation, in the sense that any administrator may remove it by simply editing the config.

Bug 1828608: Removing ImageRegistryRemoved alert

---

pkg/resource/prunercronjob.go

A value of 60 seconds might make the cronjob not to be started in time.
This patch increases the deadline to 10 minutes, as we run the pruner job
only once a day a delay increase here is acceptable.

Bug 1841080: Increasing default startingDeadlineSeconds

---

manifests/09-prometheus-rules.yaml

The operator shouldn't alert if the pruner is disabled. The alerts should be symptoms based.

Bug 1845642: Remove alert about image pruner

---

pkg/operator/bootstrap.go
pkg/storage/storage.go
pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

If operator can't reach remote swift storage bootstrap using a
persistent volume claim. Operator was doing something very similar to
this, but under certain circumstances it was not completing the
bootstrap (e.g. when swift username/password pair was not configured)

Bug 1846263: Avoiding bootstrap failure on unavailable swift

---

pkg/storage/storage.go

As part of the upcommig CSI Driver support a registry should be enabled by
default.
The CSI driver support is part of Cluster Storage Operator support in
external providers. See
https://github.com/openshift/enhancements/pull/352
Signed-off-by: Roy Golan <rgolan@redhat.com>

Enable registry by default for ovirt

---

manifests/07-operator.yaml

As we don't have two containers running on this POD anymore there is no
need to have this shared namespace.

Removed shared process namespace

---

pkg/operator/controllerimagepruner.go
pkg/resource/prunercronjob.go

This commit disables retries on pruning jobs, it also uses now the last
finished job status when checking for Condition (the operator becomes
deprecated only if the last finished job failed).

Bug 1857684: Using last finished job status and disabling retries

---

pkg/storage/gcs/gcs.go

ErrBucketNotExist is never of type
"google.golang.org/api/googleapi".Error
Removed an unused piece code as well.

Bug 1870513: Fix wrong usage of ErrBucketNotExist

---

manifests/07-operator.yaml

Cluster version operator treats unset pointers in manifests as "operator
maintainers have no opinion". If we want to actually clear this, we
need explicitly set shareProcessNamespace to false. As this property was
set to true we need now to set it to false.
For reference https://github.com/openshift/cluster-image-registry-operator/pull/587#discussion_r472576936

Bug 1857782: Setting shareProcessNamespace to false

---

pkg/storage/azure/azure.go
pkg/storage/azure/azure_test.go

Yak shaving for future implementation of storage ManagementState.

Bug 1833109: Refactoring for Azure Driver

---

pkg/client/operatorclient.go

The result of GetOperatorState is used by different controllers to
report about their conditions, sometimes they mutate the returned value.
Listers return pointer to the same value if Get is used multiple times
and the object didn't change between calls.
It means that the clients of GetOperatorState could mutate the same
object without any synchronization. In some cases it caused panics.

Bug 1876961: Fix "slice index out of range"

---

pkg/operator/bootstrap.go
pkg/operator/bootstrap_test.go
pkg/operator/complete.go
pkg/operator/controller.go
test/e2e/configuration_test.go

This PR have two purposes:
1. it reduces the risk of failing to bootstrap the image registry config
2. it ensures that httpSecret is set even if the config object is created by someone else

Bug 1824834: httpSecret should be generated when it is not set

---

pkg/operator/controllerimagepruner.go
pkg/resource/prunercronjob.go

**DUE TO CONFLICTS THIS GOT MANUALLY CHERRY PICKED FROM https://github.com/openshift/cluster-image-registry-operator/pull/586**
This commit disables retries on pruning jobs, it also uses now the last
finished job status when checking for Condition (the operator becomes
deprecated only if the last finished job failed).

[release-4.4] Bug 1873534: Using last finished job and disabling retries

---

pkg/operator/controller.go
test/e2e/bootstrap_test.go

We have multiple controllers concurrently writting the status of the
config, this commit introduces retries in case of any of them updated
the config resource before us. This is clearly a workaround, as the
main controller may create storage if we fail to update the
configuration here it may ended up creating storage again on the next
cycle, hence the need to make sure we succeed.

Bug 1857246: Retrying in case of conflict during Config update

---

pkg/operator/controller.go

This type casting is not needed as it goes right after the previous one which is made in a proper way.

Bug 1879426: Remove unsafe type casting

---

manifests/09-prometheus-rules.yaml
pkg/metrics/metrics.go
pkg/metrics/server.go
pkg/operator/status.go

1. Do not degrade the operator on job failures
2. Uses alerting instead of degrading the operator

Bug 1879176: Alerting on failed image prune job

---

Dockerfile

Updating ose-cluster-image-registry-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cluster-image-registry-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating ose-cluster-image-registry-operator builder & base images to be consistent with ART

---

pkg/storage/azure/azure.go

When the operator fails to create an Azure storage container, it panics in attempt to format the error reason.

Bug 1886849: panic during creation of Azure storage container

---

manifests/09-prometheus-rules.yaml

Creating a record rule keeping track of the number of repository imports
using registry v1 protocol.

Bug 1885856: Creating prometheus record rule for v1 imports

---

pkg/client/operatorclient.go
pkg/operator/nodecadaemon.go
pkg/resource/nodecadaemon.go
pkg/resource/nodecadaemon_test.go
test/e2e/nodecadaemon_test.go

The PR makes the operator to detect when the daemonset is changed and stomp these changes.

Bug 1850465: Keep node-ca daemonset in-sync with reference version

---

manifests/0000_90_cluster-image-registry-operator_00_servicemonitor-rbac.yaml
manifests/0000_90_cluster-image-registry-operator_01_operand-servicemonitor.yaml
manifests/0000_90_cluster-image-registry-operator_02_operator-servicemonitor.yaml
manifests/01-namespace.yaml
manifests/01-registry-credentials-request-azure.yaml
manifests/01-registry-credentials-request-gcs.yaml
manifests/01-registry-credentials-request-openstack.yaml
manifests/01-registry-credentials-request.yaml
manifests/02-rbac.yaml
manifests/03-sa.yaml
manifests/04-ca-trusted.yaml
manifests/05-ca-rbac.yaml
manifests/06-ca-serviceaccount.yaml
manifests/07-operator-service.yaml
manifests/07-operator.yaml
manifests/08-clusteroperator.yaml
manifests/09-prometheus-rules.yaml

This is matches openshift/enhancements#414 and doesn't change existing behavior

add current profile annotations to CVO manifests

---

pkg/client/listers.go
pkg/operator/controllerimagepruner.go
pkg/operator/starter.go
pkg/resource/generatorimagepruner.go
pkg/resource/prunercronjob.go
test/e2e/pruner_test.go

If the image pruner is not provided with a registry hostname, it tries to guess it from image streams. But they might be missing on fresh clusters without the samples operator. To avoid this problem, the operator should provide the pruner with the registry hostname.

Bug 1887010: Make pruner always aware of registry name

---

cmd/cluster-image-registry-operator/main.go
images/bin/entrypoint.sh
manifests/07-operator.yaml
test/e2e/emptydir_test.go

In 4.6 we've lost entrypoint script. This PR restores it and adds tests to avoid future regressions.

Bug 1892799: Operator should use entrypoint script

---

pkg/resource/prunercronjob.go
pkg/resource/prunercronjob_test.go

Log level 2 causes `oc adm prune images` to print stack traces for goroutines in case of an error. This makes the last chunk of logs meaningless, but only this chunk is available in the termination message.

Bug 1894677: Reduce default log level for pruner

---

pkg/resource/podtemplatespec.go

When the registry is restarted, it already has content in the ca-trust extracted directory from the previous run. So `mkdir` shouldn't fail when directories already exist.

Bug 1897520: Use mkdir -p to create ca-trust directories

---

manifests/0000_90_cluster-image-registry-operator_00_servicemonitor-rbac.yaml
manifests/0000_90_cluster-image-registry-operator_01_operand-servicemonitor.yaml
manifests/0000_90_cluster-image-registry-operator_02_operator-servicemonitor.yaml
manifests/01-namespace.yaml
manifests/01-registry-credentials-request-azure.yaml
manifests/01-registry-credentials-request-gcs.yaml
manifests/01-registry-credentials-request-openstack.yaml
manifests/01-registry-credentials-request.yaml
manifests/02-rbac.yaml
manifests/03-sa.yaml
manifests/04-ca-trusted.yaml
manifests/05-ca-rbac.yaml
manifests/06-ca-serviceaccount.yaml
manifests/07-operator-service.yaml
manifests/07-operator.yaml
manifests/08-clusteroperator.yaml
manifests/09-prometheus-rules.yaml

This partially implements phase 1 of openshift/enhancements#482
and does not change behavior. Initially, all cluster-image-registry-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.

Annotate manifests for single-node-developer cluster profile

---

go.mod
pkg/operator/status.go
pkg/operator/status_test.go
pkg/resource/deployment.go

Report this operator as Degraded if there is no replica or less replicas
then specified on the configuration for more than one minute.

Bug 1889921: Reporting degraded if not available

---

pkg/client/fake/fixtures.go
pkg/client/listers.go
pkg/defaults/defaults.go
pkg/operator/controller.go
pkg/operator/starter.go
pkg/storage/s3/s3.go
test/framework/mock/listers/listers.go

When a cluster is installed in a AWS C2S region, access to the AWS API requires a custom CA bundle for trust. The custom CA bundle is read from the "ca-bundle.pem" key of the kube-cloud-config ConfigMap in the openshift-config-managed namespace.
https://issues.redhat.com/browse/CORS-1584

CORS-1584: support custom CA bundle for AWS API

---

pkg/storage/s3/s3.go

Using the very same timeouts present on http.DefaultTransport into our
custom http client Transport.

Bug 1902091: Using http.DefaultTransport timeouts

---

pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

This commit makes Status.Storage.Swift to reflect Spec.Storage.Swift
when the provided container already exists. Prior to this status was
only kept in sync when the container was created.

Bug 1907202: Sync status to spec with regards to Swift config

---

manifests/01-registry-credentials-request.yaml

s3:ListMultipartUploadParts is needed to be able to check on status of uploads. The permission is implied when the IAM user/credentials that created the MultiPartUploads is the same as the user/credentials trying to list them (see https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuAndPermissions.html ).
When users/credentials are rotated, there can be a disconnect between the user/creds performing the ListMultipartUploadParts and the user/creds performing the uploads.
Stop depending on the ListMultipartUploadParts permission being implicitly granted, and just explicitly list this permission as required to allow credentials rotation without a risk of losing the ability to s3:ListMultipartuploadParts.

Bug 1915041: add ListMultipartUploadParts permission

---

bindata/nodecadaemon.yaml
pkg/assets/bindata.go

This commit adds runAsUser and runAsGroup directives to the node-ca daemonset configuration.

Bug 1914407: Explicitly set node-ca runAsUser and runAsGroup

---

manifests/01-registry-credentials-request.yaml
manifests/07-operator.yaml
pkg/resource/deployment_test.go
pkg/resource/podtemplatespec.go
pkg/resource/podtemplatespec_test.go
pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go
test/e2e/aws_test.go

In order to support alternative AWS authentication mechanisms beyond just access/secret key authentication:
With these changes (and the corresponding image-registry support), it should now be possible to use web identity token authentication. This requires:
- setting up an AWS OpenID identity provider that trusts the cluster's OIDC provider
- creating an AWS IAM Role with the permissions requested in this repo's CredentialsRequest
- granting both ServiceAccounts 'registry' and 'cluster-image-registry-operator' to be allowed to assume the AWS IAM Role
- setting up the Secret holding the AWS credentials (installer-cloud-credentials) so that the 'credentials' field contains a working AWS configuration:
```
[default]
role_arn = arn:aws:iam:ACCOUNT_NUM:role/ROLE_NAME
web_identity_token_file = …
```

Bug 1921909: build and use AWS config file for operator and operand

---

pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

**This is a copy of https://github.com/openshift/cluster-image-registry-operator/pull/653 test code was different, requiring some adjustments**
This commit makes Status.Storage.Swift to reflect Spec.Storage.Swift
when the provided container already exists. Prior to this status was
only kept in sync when the container was created.

[release-4.5] Bug 1916859: Sync status to spec with regards to Swift config

---

pkg/storage/azure/azure.go

Storage accounts V1 are being deprecated by Azure. This commit makes
this operator to create a V2 account instead. Registry is version
agnostic and works with both StorageAccounts V1 or V2.
CheckNameAvailability returns false if an account exists with the same
name in any of the versions, this allows cluster updates to move on.

Bug 1929654: Creating StorageAccount V2 instead of V1

---

bindata/nodecadaemon.yaml
pkg/assets/bindata.go
pkg/operator/nodecadaemon.go

This PR changes maxUnavailable for the node-ca daemon set, and also adds a new Available condition for this daemon set.

Bug 1933180: Allow more node-ca unavailable replicas during upgrade

---

manifests/01-registry-credentials-request.yaml

For a new way of managing OpenShift credentials on AWS to work, using Security
Token Service, we need external tooling to know the service account names from
the Credentials Request manifest so that it can create IAM Roles that can be
assumed only by those specific service accounts.
Managing credentials using STS ref: https://github.com/openshift/cloud-credential-operator/blob/master/docs/sts.md
Tooling design ref: https://issues.redhat.com/browse/CCO-60
/cc @joelddiaz

Add service account names to credentials request manifest

---

bindata/nodecadaemon.yaml
manifests/01-namespace.yaml
manifests/07-operator-ibm-cloud-managed.yaml
manifests/07-operator.yaml
pkg/assets/bindata.go
pkg/defaults/defaults.go
pkg/resource/podtemplatespec.go

In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.

Add management workload annotations

---

pkg/resource/deployment.go
pkg/resource/podtemplatespec.go

Instead of using Preferred we now use Required pod anti-affinity. This
way we can enforce image-registry pods to do not run on the same node
at the same time, this at a price of restricting the max number of pods
to to the total amount of worker nodes.

Bug 1945387: Setting required pod anti-affinity rules

---

pkg/resource/prunercronjob.go

Following other components of this operator we start setting the
priority class name to "system-cluster-critical".

Bug 1954891: Setting PriorityClassName for pruner cronjob

---

manifests/0000_90_cluster-image-registry-operator_02_operator-servicemonitor.yaml

Invalid selector makes CVO apply this manifest on every sync iteration

Bug 1960330: manifests: fix selector in image-registry-operator

---

pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

Driver config must be used for user input only and the operator shouldn't modify it using values from clouds.yaml.
This commit ensures that driver config stays unchanged, and it's used just to update default values provided by clouds.yaml.

Bug 1937464: Swift: Do not modify driver config

---

pkg/client/clients.go
pkg/client/listers.go
pkg/operator/controller.go
pkg/operator/controllerimagepruner.go
pkg/operator/status.go
pkg/resource/generator.go
pkg/resource/poddisruptionbudget.go
pkg/resource/prunercronjob.go

'policy/v1beta1 PodDisruptionBudget' and 'batch/v1beta1 CronJob' are deprecated, so we need to migrate to their v1 versions.

Bug 1966459: Use batch/v1 and policy/v1

---

pkg/storage/s3/s3.go

**Due to conflicts this is a manual backport of https://github.com/openshift/cluster-image-registry-operator/pull/648**
Using the very same timeouts present on http.DefaultTransport into our
custom http client Transport.

[release-4.6] Bug 1959563: Using http.DefaultTransport timeouts

---

pkg/resource/clusterrole.go

Allows service account used by image-registry to access ICSP objects.

Bug 1918376: Allowing system:registry to list ICSP rules

---

pkg/resource/prunercronjob.go

This fixes properly setting custom tolerations defined in imagepruner CR to the CronJob spec.

Bug 1973318: Properly set custom tolerations

---

manifests/09-prometheus-rules.yaml

The metric apiserver_v1_image_imports_total is going to be removed from the API server by https://github.com/openshift/openshift-apiserver/pull/222

Bug 1974651: Remove :apiserver_v1_image_imports:sum

---

pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

This enables image-registry's Swift storage backend to authenticate using application credentials.
Related to https://issues.redhat.com/browse/OSASINFRA-1934

Bug 1998432: Support Swift authentication using application credentials

---

manifests/01-namespace.yaml

Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-image-registry` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz

podsecurity: enforce privileged for openshift-image-registry namespace

---

test/e2e/removed_test.go

If the test build fails, dump relevant build information to the log.

e2e: Dump build information on failure

---

pkg/operator/controller.go
pkg/operator/controllerimagepruner.go
pkg/resource/caconfig.go

The operator used to be run with loglevel 0, but the current default is
2. This change updates loglevel for debug messages to keep them hidden
by default.

Bug 2039170: Change log level for debug messages

---

manifests/01-registry-credentials-request-alibaba.yaml

Adding necessary permissions to enable KMS key encryption in the registry.

Bug 2048214: Alibaba: adding permissions for using KMS encryption

---

pkg/resource/configoverrides.go
pkg/resource/deployment.go
pkg/resource/podtemplatespec.go
pkg/resource/podtemplatespec_test.go

We are using config.spec.unsupportedConfigOverrides to allow users to override image registry runtimeClass and annotations. This commit also uses OnRootMismatch for fsGroupChangePolicy in the registry deployment.

Bug 2067995: Deployment annotations, runtimeClassName override and fs policy change

---

manifests/09-prometheus-rules-imagestreams.yaml

Create a record rule to collect the amount of image stream tags present
in the cluster.

Bug 2009352: IR-120: Add prometheus rules for image stream tags rules

---

manifests/01-registry-credentials-request-ibmcos.yaml

IBM Cloud COS now requires access to Admin level role in order to
access COS HMAC keys during image-registry COS resource creation.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2082492

Bug 2082492: IBMCloud: Add admin permissions to CR

---

Makefile

The current version doesn't work with go1.18. This fix is needed for #782.

Bump golangci-lint

---

pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go

In some AWS regions S3 does not have a dual-stack endpoint. In these regions the operator should fallback to the standard endpoint.

Bug 2083466: Disable dualstack when it is not available

---

pkg/operator/nodecadaemon.go
pkg/resource/nodecadaemon.go

Continue to see failures in Managed cluster should start all core operator due to NodeCADaemonControllerDegraded.  Adding logging to investigate further
https://sippy.dptools.openshift.org/sippy-ng/jobs/4.12/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22failed_test_names%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22%5Bsig-arch%5D%5BEarly%5D%20Managed%20cluster%20should%20start%20all%20core%20operators%20%5BSkipped%3ADisconnected%5D%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D%22%7D%2C%7B%22columnField%22%3A%22variants%22%2C%22not%22%3Atrue%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22never-stable%22%7D%2C%7B%22columnField%22%3A%22variants%22%2C%22not%22%3Atrue%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22techpreview%22%7D%5D%2C%2 …

Bug 2093440: Use actualDaemonSet for SetDaemonSetGeneration

---

manifests/07-operator-ibm-cloud-managed.yaml
manifests/07-operator.yaml
pkg/operator/controller.go
pkg/operator/nodecadaemon.go
pkg/operator/starter.go
pkg/resource/deployment.go
pkg/resource/generator.go
pkg/resource/nodecadaemon.go
pkg/resource/nodecadaemon_test.go

While investigating caches not synched error it was noted that the code was using a logging event recorder.  A request was made at that time to update the event recorder to increase observability and CI signal as we likely would have caught the frequent updating vi our CI testing.

Bug OCPBUGS-716: Add support for kube event recorder

---

go.mod
go.sum
vendor/github.com/gophercloud/gophercloud/.zuul.yaml
vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/results.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
vendor/github.com/gophercloud/gophercloud/provider_client.go
vendor/modules.txt

Gophercloud v0.17.0 has an issue that causes it to fail when talking to a swift endpoint speaking HTTP2. This prevented CIRO from properly detecting available swift service, and thus forced it to failover to a cinder volume even when swift was available to the tenant.
Bumping gophercloud to v0.18.0 fixes the issue.

OCPBUGS-2941: Bump gophercloud

---

pkg/operator/status.go

a customer reported seeing this on OCP 4.10 - not sure why it hasn't shown up before tbh

OCPBUGS-3974: check for nil pointer before dereferencing

---

go.mod
go.sum
vendor/github.com/gophercloud/gophercloud/.zuul.yaml
vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/results.go
vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
vendor/github.com/gophercloud/gophercloud/provider_client.go
vendor/modules.txt

Gophercloud v0.17.0 has an issue that causes it to fail when talking to a swift endpoint speaking HTTP2. This prevented CIRO from properly detecting available swift service, and thus forced it to failover to a cinder volume even when swift was available to the tenant.
Bumping gophercloud to v0.18.0 fixes the issue.
Manual cherry-pick of #808 onto release-4.12.

OCPBUGS-3175: Bump gophercloud

---

pkg/storage/storage.go
pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

The function IsSwiftEnabled probes a connection to Swift to determine whether CIRO should fall back to using a persistent volume claim as a storage backend. This function runs on the OpenStack platform to provide an alternative solution for when Swift is not available.
Before this patch, any failure to communicate with Swift would make CIRO fall back to using a PVC. However, a failure to probing Swift could come from a temporary failure to reach the OpenStack API.
With this patch, when an issue with the connection to the OpenStack identity service is not allowing CIRO to probe Swift, the probing reports an error instead of directly falling back to Swift.
As a consequence, after this patch, temporary failures in early steps of the connection to Swift, do not make CIRO fall back to using …

OCPBUGS-4090: swift: Retry connecting to OpenStack

---

pkg/storage/swift/swift.go

This commit makes sure the Proxy env vars
are used when authenticating with OpenStack
API.

OCPBUGS-6175: OpenStack: Add support for Proxy

---

Makefile
pkg/storage/storage.go
pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

This is a cherry-pick of https://github.com/openshift/cluster-image-registry-operator/pull/830
This PR also cherry-picks https://github.com/openshift/cluster-image-registry-operator/pull/783 because older versions of `gosimple` trigger errors on my code, requiring it to be less explicit.
---
The function IsSwiftEnabled probes a connection to Swift to determine whether CIRO should fall back to using a persistent volume claim as a storage backend. This function runs on the OpenStack platform to provide an alternative solution for when Swift is not available.
Before this patch, any failure to communicate with Swift would make CIRO fall back to using a PVC. However, a failure to probing Swift could come from a temporary failure to reach the OpenStack API.
With this patch, when an issue with …

[release-4.10] OCPBUGS-5974: swift: Retry connecting to OpenStack

---

Makefile
pkg/storage/storage.go
pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

This is a manual cherry-pick of https://github.com/openshift/cluster-image-registry-operator/pull/832
---
The function IsSwiftEnabled probes a connection to Swift to determine whether CIRO should fall back to using a persistent volume claim as a storage backend. This function runs on the OpenStack platform to provide an alternative solution for when Swift is not available.
Before this patch, any failure to communicate with Swift would make CIRO fall back to using a PVC. However, a failure to probing Swift could come from a temporary failure to reach the OpenStack API.
With this patch, when an issue with the connection to the OpenStack identity service is not allowing CIRO to probe Swift, the probing reports an error instead of directly falling back to Swift.
As a consequence, after this …

OCPBUGS-7371: swift: Retry connecting to OpenStack

---

.ci-operator.yaml
Dockerfile
Makefile
cmd/cluster-image-registry-operator/main.go

Also bump golangci-lint, and fix a deprecation error.
* golangci-lint bug that required upgrade: https://github.com/golangci/golangci-lint/issues/3565
* deprecation error and the choice to simply removed the call: https://pkg.go.dev/math/rand#Seed

OCPBUGS-12132: Updating ose-cluster-image-registry-operator images to be consistent with ART

---

.github/dependabot.yml

There's no way I know to check that enabling dependabot this way will work without any settings change (although github docs suggest it will work). I tested this on my fork and it happily created a PR so it works there at least (it is disabled on forks by default tho, for obvious reasons).

.github: configure dependabot

---

pkg/defaults/defaults.go
pkg/operator/imageregistrycertificates.go
pkg/resource/generator.go
pkg/resource/imageregistryca.go

Took Flavian's work on the current PR, and fixed the configmap already exists bug. This should be good to go in tandem with:  https://github.com/openshift/machine-config-operator/pull/3770

IR-390: Make a configmap for MCO to consume CAs

---

pkg/storage/gcs/gcp_labels_tags.go
pkg/storage/gcs/gcs.go

PR has the changes for https://github.com/openshift/enhancements/pull/1217 proposed to support GCP labels in OCP, which requires cluster-image-registry-operator to add gcp userLabels available in the status sub resource of infrastructure CR, to the gcp buckets created by the operator.

CFE-682 : Add user defined labels to the GCP buckets created

---

manifests/01-registry-credentials-request-azure.yaml

Utilizes new `CredentialsRequests` API field `dataPermissions` for necessary blob data actions as per the `Storage Blob Data Contributor` Azure built-in role.
[IR-363](https://issues.redhat.com//browse/IR-363)
supersedes #859

IR-363: Update Azure Credentials Request manifest of the Cluster Image Registry Operator to use new API field for requesting permissions

---

bindata/assets.go
bindata/nodecadaemon.yaml
pkg/operator/nodecadaemon.go
pkg/resource/nodecadaemon.go
pkg/resource/nodecadaemon_test.go
test/e2e/aws_test.go
test/e2e/graceful_shutdown_test.go
test/e2e/nodecadaemon_test.go
test/e2e/pruner_test.go
test/framework/daemonset.go
test/framework/imageregistry.go

Reverts openshift/cluster-image-registry-operator#867
I think Hypershift conformance is breaking on this https://issues.redhat.com/browse/TRT-1193 blocking nightlies
https://testgrid.k8s.io/redhat-hypershift#4.14-aws-ovn-conformance&width=20
Images failing to pull from the local registry during conformance tests.
`registry` pod logs show lots of `remote error: tls: bad certificate` where there were none before.

TRT-1193: Revert "IR-373: remove node-ca daemon"

---

pkg/resource/clusterrole.go

Fix the permission [failure](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6/1683491930010292224/artifacts/e2e-metal-ipi-ovn-ipv6/gather-extra/artifacts/pods/openshift-image-registry_image-registry-6c5b5c794b-6nn7w_registry.log) caused by https://github.com/openshift/image-registry/pull/346

OCPBUGS-17882: Add rbac permission IDMS, ITMS

---

manifests/0000_90_cluster-image-registry-operator_00_servicemonitor-rbac.yaml
manifests/0000_90_cluster-image-registry-operator_01_operand-servicemonitor.yaml
manifests/0000_90_cluster-image-registry-operator_02_operator-servicemonitor.yaml
manifests/01-namespace.yaml
manifests/01-registry-credentials-request-alibaba.yaml
manifests/01-registry-credentials-request-azure.yaml
manifests/01-registry-credentials-request-gcs.yaml
manifests/01-registry-credentials-request-ibmcos.yaml
manifests/01-registry-credentials-request-openstack.yaml
manifests/01-registry-credentials-request-powervs.yaml
manifests/01-registry-credentials-request.yaml
manifests/02-rbac.yaml
manifests/03-sa.yaml
manifests/04-ca-trusted.yaml
manifests/05-ca-rbac.yaml
manifests/06-ca-serviceaccount.yaml
manifests/07-operator-ibm-cloud-managed.yaml
manifests/07-operator-service.yaml
manifests/07-operator.yaml
manifests/08-clusteroperator.yaml
manifests/09-prometheus-rules-imagestreams.yaml
manifests/09-prometheus-rules-registry-operations.yaml
manifests/09-prometheus-rules.yaml
manifests/image-references
profile-patches/ibm-cloud-managed/07-operator.yaml-patch

Add capability annotation to manifests to make image registry optional

OCPVE-632: add capability annotations to manifests

---

pkg/storage/azure/cached_key.go

make it 20 minutes instead of 5.
Azure has an api limit for storage account list (which apparently listing keys uses behind the scenes) of 100 calls / 5 minutes. if a project has a lot of clusters, this limit might be hit.

OCPBUGS-18469: increase storage account key cache expiration

---

pkg/resource/generatorimagepruner.go
pkg/resource/prunerclusterrole.go
pkg/resource/prunerclusterrole_test.go

Needs to be tested together with https://github.com/openshift/openshift-apiserver/pull/391.
I'm not sure how to reproduce the associated bug, it's intermittent and seems related to the pruner running during the upgrade. I'd be satisfied with running regression tests for this and if the bug is seen again allow users to reopen the Jira ticket.

OCPBUGS-18969: move pruner role creation from openshift-apiserver

---

pkg/metrics/server.go

Looks like [CVE-2023-39325](https://github.com/advisories/GHSA-4374-p667-p6c8) and [CVE-2023-44487](https://github.com/advisories/GHSA-qppj-fm5r-hxr3) may not have been fully mitigated by recent go patches (see https://github.com/golang/go/issues/63417#issuecomment-1758858612).
From [Go docs](https://pkg.go.dev/net/http#hdr-HTTP_2):
> Starting with Go 1.6, the http package has transparent support for the HTTP/2 protocol when using HTTPS. Programs that must disable HTTP/2 can do so by setting Transport.TLSNextProto (for clients) or Server.TLSNextProto (for servers) to a non-nil, empty map.
To minimize risk, we're disabling HTTP/2 in the metrics endpoint.

OCPBUGS-21853: disable http2 for metrics endpoint

---

pkg/storage/swift/swift.go
pkg/storage/swift/swift_test.go

Previously the validation required both user/pass AND application credentials to be provided.
This allows users to use one OR the other.

OCPBUGS-2889: accept user/pass OR application credentials on Swift UPI secret

---

manifests/02-rbac.yaml
pkg/resource/prunerclusterrole.go

Where unsure, replaced * with a list of all supported verbs.
---
These changes only affect the registry operator, the pruner and the registry itself.
All parts of the operator lifecycle are affected, including but not exclusively:
* bootstrapping
* creation of image registry resources
* removal (i.e setting operator management to "Removed")
* creating a managing pruner cronjob
* etc
Verification for this change should minimally involve regression testing for the operator, pruner and registry.

OCPBUGS-11624: manifests/02-rbac.yaml: stop using wild cards

---

bindata/nodecadaemon.yaml
manifests/07-operator-ibm-cloud-managed.yaml
manifests/07-operator.yaml
pkg/resource/podtemplatespec.go

All openshift operators must include FallbackToLogsOnError to ease debugging.

OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

---

pkg/storage/s3/s3.go
test/e2e/aws_test.go

using this setting enables a key to be used for the entire bucket instead of AWS creating one key per object.
for more info see
https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-key.html.
---
* create a cluster (don't use cluster-bot unless you can access the AWS console for it)
* create a KMS key (use the defaults)
* copy the key id (ARN)
* add the registry IAM users to the list of users in your KMS key (if you skip this step you will get 500 Internal Server Error from the registry when you try to push images!)
* edit the operator config and set .spec.storage.s3.keyID to your key id,
mine was "arn:aws:kms:ap-northeast-1:942491940283:key/da77a03c-692e-497d-bef6-d5da91e50f58", yours will be different.
* verify that the bucket "Bucket Key" is "Enabled" by going to the bucket on …

OCPBUGS-28225: pkg/storage/s3: enable bucket key on encryption settings

---

Makefile
pkg/operator/finalizer.go
pkg/storage/ibmcos/ibmcos.go
pkg/storage/oss/oss.go
pkg/storage/s3/s3.go
test/e2e/aws_test.go
test/e2e/azure_test.go

NO-JIRA: bump golangci-lint to v1.56.2

---

bindata/nodecadaemon.yaml
manifests/07-operator-ibm-cloud-managed.yaml
manifests/07-operator.yaml
pkg/resource/azurepathfixjob.go
pkg/resource/deployment.go
pkg/resource/prunercronjob.go

This affects the following workloads:
- `cluster-image-registry-operator` deployment
- `image-pruner` cronjob
- `image-registry` deployment
- `node-ca` daemonset

AUTH-482: set required-scc for openshift workloads

---

cmd/move-blobs/main.go

our validation was incorrect - when account key is given client and
tenant ids are not required

OCPBUGS-32328: azure-path-fix: support auth via account key (without clientID)

---

pkg/resource/podtemplatespec_test.go
pkg/storage/ibmcos/ibmcos.go
pkg/storage/ibmcos/ibmcos_test.go
pkg/storage/s3/s3.go
pkg/storage/s3/s3_test.go

the latest upgrade of our openshift/docker-distribution fork brought in a patch introducing `forcepathstyle` configuration, which was mistakenly merged the openshift only `virtualhostedstyle` configuration.
to workaround the issue we simply drop the use of `virtualhostedstyle` in favour of `forcepathstyle`.
we will eventually remove our custom `virtualhostedstyle` path from our docker-distribution fork, but using
`.spec.storage.s3.virtualHostedStyle` should work as expected regardless.

OCPBUGS-32710: pkg/storage/s3: use force path style in favour of virtual hosted style config

---

manifests/01-registry-credentials-request-gcs.yaml
pkg/storage/gcs/gcp_labels_tags.go
pkg/storage/gcs/gcp_labels_tags_test.go
pkg/storage/gcs/gcs.go

PR contains below changes:
- GCP Resource tags specific code refactoring to mock services to add unit test cases.
- Added permissions required for fetching tags and creating tag bindings.
- Removed checks for unsupported regions `us-east2` and `us-east3`, as these are not officially regions and restriction has also been removed from bucket doc [here](https://cloud.google.com/storage/docs/tags-and-labels#tags)

CFE-962: Refactor code to mock GCP tag service for UTs

---

manifests/02-rbac.yaml
pkg/resource/clusterrole.go

Add `subjectaccessreviews` capability to operator and registry.
SSAR doesn't work anymore with [AUTH-509](https://issues.redhat.com/browse/AUTH-509), but we can do a SAR instead and specifying the user / group as anonymous.
In order for the image-registry to be able to create a SAR, we need this change.

OCPBUGS-33453: add SAR capability to image-registry

---

pkg/operator/azurepathfixcontroller.go
pkg/resource/azurepathfixjob.go

removes the job if it exists, and does nothing when it doesn't. we added this job to help users work around a breaking change in the uptsream distribution azure storage driver that changed the root storage path.
this is no longer needed at this point, so we remove it.
/assign @dmage

IR-477: pkg/operator: deactivate azure path fix job

---

bindata/nodecadaemon.yaml
manifests/07-operator-ibm-cloud-managed.yaml
manifests/07-operator.yaml
pkg/resource/azurepathfixjob.go
pkg/resource/deployment.go
pkg/resource/prunercronjob.go

[OCPBUGS-36325](https://issues.redhat.com/browse/OCPBUGS-36325)
Manual cherry-pick of [#1008](https://github.com/openshift/cluster-image-registry-operator/pull/1008)

[release-4.15] OCPBUGS-36325: Set required-scc for openshift workloads

---

pkg/storage/ibmcos/ibmcos.go

Power VS endpoint validation in the API only allows for lower case characters. However, the endpoint struct we check against is hardcoded to be PascalCase. This patch checks against the lower case version of the string to ensure it's recognized.

OCPBUGS-37207: Power VS: Check endpoints against lower case strings

---

pkg/resource/podtemplatespec.go

using this might help keep write permissions on
/etc/pki/ca-trust/extracted/pem/directory-hash.

OCPBUGS-38842: pkg/resource: invoke update-ca-trust extract with --output

---

pkg/resource/azurepathfixjob.go
pkg/resource/podtemplatespec.go

manual cherry pick to include both required commits.
overrides https://github.com/openshift/cluster-image-registry-operator/pull/1099

[release-4.15] OCPBUGS-38895: pkg/resource: invoke update-ca-trust extract with --output

---

pkg/operator/azurepathfixcontroller.go

or when the operator is removed.
This will also stop the azure-path-fix controller from running when users have configured storage other than azure.

[release-4.16]  OCPBUGS-41903: pkg/operator/azurepathfixcontroller: do not sync on non-azure storage

---

pkg/operator/azurepathfixcontroller.go

Reverts openshift/cluster-image-registry-operator#1115

Revert "[release-4.16]  OCPBUGS-41903: pkg/operator/azurepathfixcontroller: do not sync on non-azure storage"

---

pkg/storage/azure/azure.go
pkg/storage/azure/azureclient/azureclient.go

HyperShift will pass a client ID through an environment variable, ARO_HCP_MI_CLIENT_ID, when it deploys the cluster-image-registry operator on a hosted control plane. This client ID will be used to create a new managed identity to authenticate with Azure on the hosted control plane.

OCPBUGS-42004: Set the Managed Identity client ID

---

pkg/storage/azure/azure.go
pkg/storage/azure/azureclient/azureclient.go

the previous tag key seems to no longer be added to clusters created using the cluster-api since 4.17.
---
Making it WIP because we're not sure if this is the right way to go, or if the installer should be backwards compatible and continue tagging the vnet using the previous format.

OCPBUGS-42196: pkg/storage/azure: use cluster-api tag key to discover vnet

---

pkg/storage/azure/azureclient/azureclient.go
pkg/storage/azure/azureclient/azureclient_test.go

different operations in Azure require different sets of credentials. some operations for example only need a storage account key to authenticate with Azure API.
since we cannot predict which operation the caller will need, we cannot validate auth related options on client instantiation time.
this didn't use to be an issue because the client was only used for private endpoint configuration, which did not use account key for auth, so validation was more predictable.

OCPBUGS-42514: azureclient: stop validating credentials when creating the client

---

pkg/storage/azure/azureclient/azureclient.go
pkg/storage/azure/azureclient/azureclient_test.go

This is a manual cherry pick of https://github.com/openshift/cluster-image-registry-operator/pull/1127 (automated cherry pick fail due to git conflict).
-----
different operations in Azure require different sets of credentials. some operations for example only need a storage account key to authenticate with Azure API.
since we cannot predict which operation the caller will need, we cannot validate auth related options on client instantiation time.
this didn't use to be an issue because the client was only used for private endpoint configuration, which did not use account key for auth, so validation was more predictable.

OCPBUGS-42812: azureclient: stop validating credentials when creating the client

---

pkg/storage/azure/azureclient/azureclient.go
pkg/storage/azure/azureclient/azureclient_test.go

Manually cherry-picking https://github.com/openshift/cluster-image-registry-operator/pull/1130 due to merge conflicts.
---
different operations in Azure require different sets of credentials. some operations for example only need a storage account key to authenticate with Azure API.
since we cannot predict which operation the caller will need, we cannot validate auth related options on client instantiation time.
this didn't use to be an issue because the client was only used for private endpoint configuration, which did not use account key for auth, so validation was more predictable.

[release-4.16] OCPBUGS-42933: azureclient: stop validating credentials when creating the client

---

pkg/operator/azurestackcloud.go
pkg/operator/imageconfig.go
pkg/operator/nodecadaemon.go

without this wait, the nodeca daemon controller would sometimes make the operator become Degraded.
the azure stack cloud and image config controllers were showing errors when the operator pod started after an upgrade, so this also adds sync waits to those.

OCPBUGS-38667: pkg/operator: wait for image registry config object cache sync

---

test/e2e/configuration_test.go
test/e2e/leaderelection_test.go
test/framework/imageregistry.go

the TestOperandProxyConfiguration job has been flakying more and more lately. analysis show that the cause is not the test itself, but cluster recovery after the test teardown runs. it seems some components need longer to recover after a change in proxy configuration.
this commit increases the timeout from 5 to 10 minutes in hopes to stabilize this test.
Also changes TestLeaderElection to assert on leader lease acquiring instead of waiting on lease message as this would at times flake.

OCPBUGS-43508: fix proxy config and leader election test flakes

---

go.mod
pkg/operator/imageconfig.go

This is a cherry-pick of #1126

[release-4.15] OCPBUGS-42930: Continuous pull-secret updates / slow initialization on build01 (test platform infrastructure)

---

manifests/09-prometheus-rules.yaml

alerts when detecting metrics for read-only filesystem and device out of space errors.
the alerts in this commit follow the conventions specified by https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md.
---
Please see the description of https://github.com/openshift/image-registry/pull/412 for steps on configuring the image registry with a read-only pvc.

IR-490: manifests: add pvc related alerts to prometheus rules

---

go.mod
go.sum
vendor/github.com/ppc64le-cloud/powervs-utils/region.go
vendor/modules.txt

The latest version of `powervs-utils` includes some new zones. Update the version to this.

MULTIARCH-5164: Update powervs-utils regions to include us-south and tor

---

pkg/storage/ibmcos/ibmcos.go

After https://github.com/openshift/api/pull/2076, the validation in the image registry operator for the Power VS platform does not match the API's expectations.  This PR reverts #1076 which intended to work around the API's initial validation issues.

OCPBUGS-47503: Power VS: Revert #1076 to match new API validation

---

pkg/storage/swift/swift.go

In openshift/cloud-credential-operator/pull/780, we have added the ability for `cloud-credential-operator` to consume a CA cert from the root credentials secret and to include in the credentials secrets it provisions.
In openshift/installer/pull/9194, we have modified the Installer to start setting this field where necessary.
Adapt `cluster-image-registry-operator` to allow it to start consuming the CA cert from this place. We maintain fallbacks for the previous locations of the cert for now, but these can be removed in the next release.
Dependencies:

OSASINFRA-3747: Prefer CA cert from credentials secret

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/github.com/golang-jwt/jwt/v5/README.md
vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
vendor/github.com/golang-jwt/jwt/v5/parser.go
vendor/github.com/golang-jwt/jwt/v5/token.go
vendor/modules.txt

Prevent https://github.com/advisories/GHSA-mh63-6h87-95cp. We are relying on
https://github.com/Azure/go-autorest that has been archived and isn't receiving more updates. This will force us to move to a different package but we can't wait for that to happen to address the CVE therefore this PR adds a replacement on github.com/golang-jwt/jwt/v4 pointing to v4.5.2.

OCPBUGS-53867: Bump github.com/golang-jwt/jwt

---

pkg/storage/azure/azure.go
pkg/storage/azure/azure_test.go
pkg/storage/azure/azureclient/azureclient.go

This PR fixes credential caching issues in Azure storage operations and adds caching support for User Assigned Managed Identity (UAMI) credentials.
Caching at the driver level was not enough so a global cache was introduced so that we are not getting new credentials over and over from Azure.
- **fix(azure): fix credential caching key mismatch in driver storageAccountsClient** 
Resolves credential caching key inconsistencies in the storage accounts client
- **fix(azure): fix credential caching key mismatch in azureclient**
Fixes credential caching key mismatches in the Azure client implementation
- **feat(azure): add ensureUAMICredentials function with comprehensive tests**
- Adds new `ensureUAMICredentials` function to obtain and cache Azure TokenCredential using User Assigned Managed …

OCPBUGS-59734: fix(azure): resolve credential caching issues around UAMI support
